site_name: TODO API
repo_name: github.com/andreclimaco/todo-api-fast
site_url: https://andreclimaco.github.io/todo-api/
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_root_full_path: false

nav:
  - Início: index.md
  - API: autoapi.md