site_name: TODO API
repo_name: andreclimaco/todo-api-fast
repo_url: https://github.com/andreclimaco/todo-api-fast
site_url: https://andreclimaco.github.io/todo-api-fast/
theme:
  name: material
  language: pt-BR
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_root_full_path: false
  - git-revision-date-localized:
      locale: pt_BR
      enable_creation_date: true
  - git-committers:
      repository: andreclimaco/todo-api-fast
      branch: main
  - git-authors
nav:
  - index.md
  - Endpoints: endpoints.md
  - API: autoapi.md