"""cria tabelas de usuários e tarefas

Revision ID: 0e725e9e6102
Revises: 0001
Create Date: 2025-08-01 15:31:44.824371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e725e9e6102'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarefas', sa.Column('atualizada_em', sa.DateTime(), nullable=True))
    op.alter_column('tarefas', 'prioridade',
               existing_type=postgresql.ENUM('baixa', 'media', 'alta', name='prioridadeenum'),
               nullable=True,
               existing_server_default=sa.text("'media'::prioridadeenum"))
    op.alter_column('tarefas', 'status',
               existing_type=postgresql.ENUM('pendente', 'em_andamento', 'concluida', name='statusenum'),
               nullable=True,
               existing_server_default=sa.text("'pendente'::statusenum"))
    op.alter_column('tarefas', 'criado_em',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('usuarios', 'criado_em',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'criado_em',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tarefas', 'criado_em',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tarefas', 'status',
               existing_type=postgresql.ENUM('pendente', 'em_andamento', 'concluida', name='statusenum'),
               nullable=False,
               existing_server_default=sa.text("'pendente'::statusenum"))
    op.alter_column('tarefas', 'prioridade',
               existing_type=postgresql.ENUM('baixa', 'media', 'alta', name='prioridadeenum'),
               nullable=False,
               existing_server_default=sa.text("'media'::prioridadeenum"))
    op.drop_column('tarefas', 'atualizada_em')
    # ### end Alembic commands ###
